server:
  port: 9003
eureka:
  server:
    #    关闭保护模式 默认15分钟内心跳成功率低于85%进入保护模式
    enable-self-preservation: false
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false # 不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka-9001.com:9001/eureka,http://eureka-9002.com:9002/eureka
  instance: # eureak实例定义
    hostname: eureka-9003.com  # 定义Eureka实例所在的主机名称
spring:
  application:
    name: eureka-9003.com

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
